# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e107cb3dd58fd06f125a43b4500f29f20b947ed896c9013fbd17a42114350eb53f103dd5a4e878ac6f9117a33ac2f9ff525507e610cc3444581113b90cf830c

test:
  secret_key_base: 573e499b7ce059bd8ad69dec1e1906c4e07502def7bc51978cec5dce7f59a50de98fee63dd8bb86a52e0fb1a1fa54ee92a8638118c9b12fb03b55a913395803c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
